// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPO1FN27jZso_-569q90WGrLvsQHQf3Ps',
    appId: '1:23963364658:web:d62d93322500fd5330fb2b',
    messagingSenderId: '23963364658',
    projectId: 'neologism-quiz',
    authDomain: 'neologism-quiz.firebaseapp.com',
    storageBucket: 'neologism-quiz.appspot.com',
    measurementId: 'G-KPRMK06BP1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8bUtggRD9cbFcWt-MHIGJYTGPc21b35U',
    appId: '1:23963364658:android:ac06534782d96cba30fb2b',
    messagingSenderId: '23963364658',
    projectId: 'neologism-quiz',
    storageBucket: 'neologism-quiz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiYljnsUcCsDRavGfIY3HwDEsFf2h8cnY',
    appId: '1:23963364658:ios:ab7135f74c9db67f30fb2b',
    messagingSenderId: '23963364658',
    projectId: 'neologism-quiz',
    storageBucket: 'neologism-quiz.appspot.com',
    iosClientId: '23963364658-sa1ttchhlqr2am7fikse02lrmkkfbhsq.apps.googleusercontent.com',
    iosBundleId: 'com.example.neologism',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiYljnsUcCsDRavGfIY3HwDEsFf2h8cnY',
    appId: '1:23963364658:ios:ab7135f74c9db67f30fb2b',
    messagingSenderId: '23963364658',
    projectId: 'neologism-quiz',
    storageBucket: 'neologism-quiz.appspot.com',
    iosClientId: '23963364658-sa1ttchhlqr2am7fikse02lrmkkfbhsq.apps.googleusercontent.com',
    iosBundleId: 'com.example.neologism',
  );
}
