// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2W-eQ2AzMANpU2qSPBc42c_OPrpMtaOw',
    appId: '1:200024650804:web:0ea47109c881300c620661',
    messagingSenderId: '200024650804',
    projectId: 'neologismquiz',
    authDomain: 'neologismquiz.firebaseapp.com',
    storageBucket: 'neologismquiz.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFrxtDJOnV6Ci9VOLQAjqf86HnEe6JrWA',
    appId: '1:200024650804:android:9aede4f6ab30d7ef620661',
    messagingSenderId: '200024650804',
    projectId: 'neologismquiz',
    storageBucket: 'neologismquiz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW5O-5EjCuZvV2r19PucLfn-QV4S0i0sM',
    appId: '1:200024650804:ios:e48f945d32f1d26b620661',
    messagingSenderId: '200024650804',
    projectId: 'neologismquiz',
    storageBucket: 'neologismquiz.appspot.com',
    iosClientId: '200024650804-uuugc0fn9khhbvssmar9ma123iie9gau.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW5O-5EjCuZvV2r19PucLfn-QV4S0i0sM',
    appId: '1:200024650804:ios:d833cefe37573422620661',
    messagingSenderId: '200024650804',
    projectId: 'neologismquiz',
    storageBucket: 'neologismquiz.appspot.com',
    iosClientId: '200024650804-c77v6g1mnnndl76944fin5h0vkbtkf4b.apps.googleusercontent.com',
    iosBundleId: 'com.example.neologism',
  );
}
